services:
  - type: web
    name: safestreet-node-api
    env: node
    plan: free
    buildCommand: npm install && cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: "ENTER_YOUR_MONGODB_URI_HERE"
